from enum import Enum

class ErrorCode(str, Enum):
    # FIRMS Ingestion
    FIRMS_AUTH_FAILED = "FIRMS_001"
    FIRMS_RATE_LIMIT = "FIRMS_002"
    FIRMS_MALFORMED_PAYLOAD = "FIRMS_003"
    FIRMS_SENSOR_UNAVAILABLE = "FIRMS_004"
    FIRMS_INVALID_COORDINATES = "FIRMS_005"

    # Satellite Evidence
    SAT_NO_SCENE = "SAT_001"
    SAT_CLOUD_OBSCURED = "SAT_002"
    SAT_STAC_TIMEOUT = "SAT_003"
    SAT_BAND_DOWNLOAD_FAILED = "SAT_004"

    # Facility Context
    FACILITY_NOT_FOUND = "FACILITY_001"
    FACILITY_BASELINE_INSUFFICIENT = "FACILITY_002"
    OSM_QUERY_FAILED = "FACILITY_003"

    # ML & Classification
    MODEL_NOT_LOADED = "MODEL_001"
    MODEL_INFERENCE_FAILED = "MODEL_002"
    FEATURE_COMPUTATION_FAILED = "MODEL_003"
    MODEL_ABSTAINED = "MODEL_004"

    # Database & System
    DATABASE_UNAVAILABLE = "SYS_001"
    AUTH_UNAUTHORIZED = "AUTH_001"
    AUTH_FORBIDDEN = "AUTH_002"
    RESOURCE_NOT_FOUND = "SYS_002"
    VALIDATION_ERROR = "SYS_003"
